version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins-server
    hostname: server-jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    user: root
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"  # Opcional, se quiser acessar via http://localhost:8080/jenkins
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network

volumes:
  jenkins_home:

networks:
  jenkins_network:
